// <auto-generated />
namespace Kcesar.MissionLine.Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class linkToMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linkToMember));
        
        string IMigrationMetadata.Id
        {
            get { return "201506022359475_linkToMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
