// <auto-generated />
namespace Kcesar.MissionLine.Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class eventDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201506030528116_eventDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
