// <auto-generated />
namespace Kcesar.MissionLine.Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCarpooling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCarpooling));
        
        string IMigrationMetadata.Id
        {
            get { return "201806110445490_Add-Carpooling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
